-- MySQL Script generated by MySQL Workbench
-- Thu May  4 17:33:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema keywords C++
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema keywords C++
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keywords C++` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema keywords c++
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema keywords c++
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `keywords c++` DEFAULT CHARACTER SET utf8mb3 ;
USE `keywords C++` ;

-- -----------------------------------------------------
-- Table `keywords C++`.`KeywordName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords C++`.`KeywordName` (
  `Название` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Название`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keywords C++`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords C++`.`Type` (
  `Тип` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Тип`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keywords C++`.`C++ Standart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords C++`.`C++ Standart` (
  `Версия стандарта` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Версия стандарта`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keywords C++`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords C++`.`Keyword` (
  `Название` VARCHAR(45) NOT NULL,
  `Определение` VARCHAR(600) NOT NULL,
  `Синтаксис` VARCHAR(1000) NOT NULL,
  `Тип` VARCHAR(45) NOT NULL,
  `Связанные ключевые слова` VARCHAR(100) NULL,
  `Версия стандарта C++` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Название`),
  INDEX `fk_Ключевое Слово_Имя ключевого с_idx` (`Название` ASC) VISIBLE,
  INDEX `fk_Ключевое Слово_Тип1_idx` (`Тип` ASC) VISIBLE,
  INDEX `fk_Ключевое Слово_Стандарт C++1_idx` (`Версия стандарта C++` ASC) VISIBLE,
  CONSTRAINT `Ключевое Слово_Имя ключевого слова`
    FOREIGN KEY (`Название`)
    REFERENCES `keywords C++`.`KeywordName` (`Название`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ключевое Слово_Тип`
    FOREIGN KEY (`Тип`)
    REFERENCES `keywords C++`.`Type` (`Тип`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ключевое Слово_Стандарт C++`
    FOREIGN KEY (`Версия стандарта C++`)
    REFERENCES `keywords C++`.`C++ Standart` (`Версия стандарта`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `keywords C++`.`Example`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords C++`.`Example` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Номер` INT NOT NULL,
  `Текст` VARCHAR(2000) NOT NULL,
  `Ключевое Слово_Название` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Пример_Ключевое Слово1_idx` (`Ключевое Слово_Название` ASC) VISIBLE,
  CONSTRAINT `Пример_Ключевое Слово`
    FOREIGN KEY (`Ключевое Слово_Название`)
    REFERENCES `keywords C++`.`Keyword` (`Название`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `keywords c++` ;

-- -----------------------------------------------------
-- Table `keywords c++`.`ключевое слово`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords c++`.`ключевое слово` (
  `Идентификатор` VARCHAR(45) NOT NULL,
  `Определение` VARCHAR(600) NOT NULL,
  `Синтаксис` VARCHAR(1500) NOT NULL,
  `Тип` VARCHAR(45) NULL DEFAULT NULL,
  `Пример` VARCHAR(2000) NOT NULL,
  `Связанные ключевые слова` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Идентификатор`),
  UNIQUE INDEX `Идентификатор_UNIQUE` (`Идентификатор` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `keywords c++`.`пример`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `keywords c++`.`пример` (
  `Номер` INT NOT NULL,
  `Столбец1` VARCHAR(2000) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
